run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - errcheck
    - deadcode
    - revive
    - gocyclo
    - dupl
    - prealloc
    - gocritic
  disable:
    - errcheck
